### ISSUE TITLE
Hosted version not working either in Chrome nor in Firefox 52

### ISSUE THREAD

**Issue by JasonKeirstead** [mitre/attack-navigator#1]
Going to https://mitre.github.io/attack-navigator/enterprise/ results in no Matrix being loaded.

Opening developer tools shows the site trying to load some files from Github that fail due to origin policies.

**Comment by jburns12** [comment]
Hi Jason,

I talked to @johnwunder about the error you're having, and it looks like it's actually a TLS/SSL cert issue. I'm not having any luck recreating this locally, but I'm going to look into this and see if I can find a solution. I have a strong suspicion that if you're behind a proxy of some kind that it might be related.

Thanks,
Jen

**Comment by JasonKeirstead** [comment]
Hi @jburns12 , Nope not behind any proxy. I will attach a screenshot of what Chrome tells me.

**Comment by JasonKeirstead** [comment]
![image](https://user-images.githubusercontent.com/8117749/36993766-530a27fa-2085-11e8-8e11-cc14cba986b1.png)

**Comment by JasonKeirstead** [comment]
The enterprise-attack.json and pre-attack.json files are for some reason being loaded from raw.githubusercontent.com instead of from the "assets" directory, which has an invalid SSL cert and because of HSTS it is blocked 
![image](https://user-images.githubusercontent.com/8117749/36993844-9f17c828-2085-11e8-8336-8d4d9526aa30.png)

**Comment by JasonKeirstead** [comment]
I think this is an IBM issue. Closing.
