### ISSUE TITLE
Adding a button to remove all annotations on selected techniques

### ISSUE THREAD

**Issue by jburns12** [mitre/attack-navigator#12]
On click, for each selected technique, this feature would remove:
- comment
- score
- color
- enabled-disabled states

**Comment by thatfiferguy** [comment]
This feature has been implemented in [features/remove-all-annotations](https://github.com/mitre/attack-navigator/tree/features/remove-all-annotations) and merged into develop. The "deselect all" button icon has been replaced with a new icon, and the remove all annotations button icon has taken the old "deselect all" icon.
