### ISSUE TITLE
Embedding the Navigator into a webpage as a widget

### ISSUE THREAD

**Issue by jburns12** [mitre/attack-navigator#13]
This would allow a developer of other web apps and webpages to embed a Navigator instance, potentially with many of the features such as technique annotating disabled and not visible.

**Comment by thatfiferguy** [comment]
Embedding can be achieved with an iframe:
`<iframe src="https://mitre.github.io/attack-navigator/enterprise/" width="1000" height="500"></iframe>`

This is well paired with the feature defined in #20, which allows the user to specify a layer to open in the navigator by default. For example, the following iframe will embed a navigator instance showing _*bear APTs_: 
`<iframe src="https://mitre.github.io/attack-navigator/enterprise/#layerURL=https%3A%2F%2Fraw.githubusercontent.com%2Fmitre%2Fattack-navigator%2Fmaster%2Flayers%2Fdata%2Fsamples%2FBear_APT.json" width="1000" height="500"></iframe>
`
_Note: as of 20 March 2018 the layerURL feature is only present in our develop branch and therefore not present in the hosted version. The above code will be supported in a future update of our hosted instance._
