### ISSUE TITLE
Adding 'Default Layer' option

### ISSUE THREAD

**Issue by wietze** [mitre/attack-navigator#14]
This would allow a user to specify a default layer that will be shown every time the Navigator is opened, without having to manually upload it every time.

**Comment by jburns12** [comment]
Hi @wietze - this is a great idea for an enhancement, and thanks for bringing this up. We'll discuss and prioritize this feature request for integration with the Navigator based on how it fits in with our current set of enhancements slotted for our version 2 release.

We also welcome pull requests based on our `develop` branch if you or anyone else in the community wants to contribute this to the Navigator individually.

**Comment by thatfiferguy** [comment]
While it doesn't exactly match the use case you describe, issue #20 may meet some of the requirements for this issue. Once #20 is implemented you would be able to bookmark the navigator URL with a query-string specifying your desired "default layer."

**Comment by rjsmitre** [comment]
Is this something that would be configured on an instance-basis, i.e. in the Navigator config file that would apply to everyone who uses that instance?  If so, then an organization hosting a local instance of the Navigator could configure the default layer as they see fit.  Beyond that, is there a need/ability for a per-user default requiring some sort of cookie?

**Comment by wietze** [comment]
I'm mainly interested in the instance-basis version; for our team it would be great to have our ATT&CK coverage as the default layer, allowing each team member to add their own layers or do their own analysis based on that. 

The per-user version would be a nice extra. The aforementioned URL bookmark solution (#20) might cover this use case though.

**Comment by CollinFingar** [comment]
A solution for this issue has been pushed to the develop branch. You can now add a default layer file to the assets directory and specify the location in the config file. There is more documentation on the README
