### ISSUE TITLE
Release in Docker Container

### ISSUE THREAD

**Issue by jcburgoon** [mitre/attack-navigator#15]
Would it be possible to release this in a Docker container to make it easier for users to get started with the app.

**Comment by jermdw** [comment]
I could possibly assist with this issue, as I was thinking the same thing, a Docker image would be great! 😸

**Comment by jburns12** [comment]
Hi @jermdw - feel free to jump in and create a PR for this feature based on our `develop` fork. We would love assistance from the community and are happy to get your input on this as well!

**Comment by CollinFingar** [comment]
A dockerfile was added to the develop branch with documentation on running it in the README
