### ISSUE TITLE
Add Custom Multi-Select

### ISSUE THREAD

**Issue by jcburgoon** [mitre/attack-navigator#18]
Currently, all of the multi-selects are pre-defined in a drop down. It would be useful to be able to select multiple techniques at one time to toggle states, add background colors, etc.

**Comment by rjsmitre** [comment]
The Navigator currently supports manually selecting multiple techniques by SHIFT-clicking the technique (or by right-clicking on a technique and choosing "add to selection").  Are you looking for some other functionality?

**Comment by jcburgoon** [comment]
Ahh, I see. I was CTRL-clicking the techniques like you would do in Windows to select non-contiguous files. Maybe extend the functionality to include the CTRL key or close the issue... Thanks!

**Comment by jburns12** [comment]
Hey @jcburgoon ...the CTRL-click functionality is a quick add, so we'll have it implemented for version 2 of the Navigator. Thanks for the suggestion!

**Comment by thatfiferguy** [comment]
This feature has been implemented in [features/additive-selection-keys](https://github.com/mitre/attack-navigator/tree/features/additive-selection-keys) and merged into develop. CTRL (windows) and CMD (mac) can now be used to select multiple techniques just like shift (both platforms).
