### ISSUE TITLE
Printing, exporting, and rendering the matrix

### ISSUE THREAD

**Issue by jburns12** [mitre/attack-navigator#2]
Users should be able to print, export and render the current view of the matrix.

**Comment by thatfiferguy** [comment]
The feature has been implemented in [features/export-svg](https://github.com/mitre/attack-navigator/tree/features/export-svg) and merged into develop.

**Comment by thatfiferguy** [comment]
I just realized I forgot to add documentation to the help page. Reopening the issue...

**Comment by thatfiferguy** [comment]
Added documentation, merged back into develop.
