### ISSUE TITLE
Consider supporting user-defined layer legend

### ISSUE THREAD

**Issue by rjsmitre** [mitre/attack-navigator#24]
Since the Navigator (rightly) doesn't define the semantics of what particular colors are intended to denote in a layer, consider adding the ability for the user to define an optional "legend" for a layer.  This legend would allow the user to manually pick a color and associate descriptive text with that color.  For example, a user might define a legend as follows:
(selecting red) "SEVERE Risk"
(selecting yellow) "MODERATE Risk"
(selecting green) "LOW Risk"

The Navigator could include the legend on print/export and provide an interface to add/edit the legend.

**Comment by CollinFingar** [comment]
A legend was added and pushed to the develop branch. It's in the bottom right corner and is capable of displaying many items with customizable colors and labels. The legend is saved and loaded with each layer file. Check out the help page for more info.
