### ISSUE TITLE
Allow persistent layers to be stored / loaded

### ISSUE THREAD

**Issue by informationinsecurity** [mitre/attack-navigator#26]
It would be helpful to allow storage / persistence of layers that are created. For example in my installation, I have saved off layers but every time I reload the site I have to re-upload the json file. Offering to save some server side, or have a default display would be helpful.

**Comment by jburns12** [comment]
Hi @informationinsecurity - this is a great point. We have had a few others recommend similar ideas as well, so we implemented an enhancement which currently resides in our "develop" branch that should hopefully address your concern. You can check out Issue #14 for reference.

The plan is to merge this into "master" and update the github.io site accordingly in the upcoming Version 2.0 release.
