### ISSUE TITLE
Uploading a layer with an unsupported version number should alert the user

### ISSUE THREAD

**Issue by thatfiferguy** [mitre/attack-navigator#27]
If the user uploads a layer file with a version number that is not the current layer version expected by the ATT&CK Navigator, an alert should display which states that some of the layer configurations may not be restored and that the default value will be used in those fields.

**Comment by CollinFingar** [comment]
An alert is now present upon loading a layer with a version that isn't equal to the version the Navigator used. Pushed to develop.
