### ISSUE TITLE
Navigator not updating with the new tactic (Initial Access) from the April 2018 update 

### ISSUE THREAD

**Issue by nordef** [mitre/attack-navigator#29]
The navigator does not seem to update with the newest tactic added, initial access, from the April 2018 update.

**Comment by jburns12** [comment]
Hey @nordef - good timing on this issue. We just synced the tactics for the Navigator to match the April 2018 ATT&CK content release.

You may have to clear your cache to access the revised version of the Navigator that contains Initial Access. Let us know if you run into any further issues.
