### ISSUE TITLE
node.js

### ISSUE THREAD

**Issue by rocket71** [mitre/attack-navigator#46]
I know this isn't likely something mitre should address but I have spent hours trying to install NODE.JS.  There are permission issues with installing NODE.JS from the link provided from the install directions.  I still can't get past this. Thanks.

**Comment by jburns12** [comment]
Hey @rocket71 - sorry to hear that Node.JS is giving you troubles. Do you have an error log regarding the permission issues?

Also, a couple other options for using the Navigator are by accessing our GitHub Pages instance here - https://mitre.github.io/attack-navigator/enterprise/ or using Docker. You may have already seen these options, but I just wanted to point them out in case.

**Comment by jburns12** [comment]
This issue hasn't been updated in almost a month. Closing it for now unless we hear any further concerns.
