### ISSUE TITLE
Configure style for techniques with comments

### ISSUE THREAD

**Issue by johnwunder** [mitre/attack-navigator#53]
This is more a speculative idea than an actual request, but what do people think about the idea of allowing user configuration (or maybe server owner configuration beyond just editing the CSS?) of the "comment" style?

I have some autogenerated layers that provide comments for every technique in the matrix. When that happens, it makes it look very busy. I'd love to keep the comments, but just not show the yellow underline. I know I can fix this by altering the CSS, just wondering if others had run into the same thing.

**Comment by thatfiferguy** [comment]
I like this idea. All the rest of the colors used in the Navigator (tactic row header, score gradient, manually assigned colors) are completely customizable so it'd be good to allow the user to change the style (color, visibility) in case it clashes. 

For now the scss [here](https://github.com/mitre/attack-navigator/blob/master/nav-app/src/app/datatable/data-table.component.scss#L103) is where the comment style is defined.

**Comment by isaisabel** [comment]
The color of the underline can now be specified using the `comment_color` field in the config file. The comment underline can be removed through the value `"transparent"`. Non-underline styles are not currently supported as they could conflict with the rest of the Matrix UI. This feature was implemented in [feature/user-defined-metadata](https://github.com/mitre/attack-navigator/tree/feature/user-defined-metadata) and merged into develop.
