### ISSUE TITLE
Incorrect title on default layer

### ISSUE THREAD

**Issue by cvantine** [mitre/attack-navigator#54]
A default layer set in **nav-app/src/assets/config.json** will display "new layer" rather than the title defined in the layer's JSON.

### To Replicate:
1. Copy a valid JSON layer file to **attack-navigator/nav-app/src/assets/defaultLayerTest.json**
2. Set "enabled" to "true" in **attack-navigator/nav-app/src/assets/config.json** under "default_layer"
3. Restart the Navigator service (unnecessary if in dev mode)

**Comment by jburns12** [comment]
Hi @cvantine - thanks for bringing up this issue and for contributing our first external pull request! We will soon test and merge it into the project.

**Comment by isaisabel** [comment]
Merged fix into the `develop` branch. Thank you for catching the bug!
