### ISSUE TITLE
Does not build on OS X

### ISSUE THREAD

**Issue by DavidJBianco** [mitre/attack-navigator#61]
Trying to build the latest version on OS X using node 10.9.0.  I'm getting the following error building fsevents:

> > fsevents@1.1.3 install /Users/z002l4q/TEMP/attack-navigator-docker/attack-navigator/nav-app/node_modules/fsevents
> > node install
> 
> node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.9.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
> node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.9.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
>   SOLINK_MODULE(target) Release/.node
>   SOLINK_MODULE(target) Release/.node
>   CXX(target) Release/obj.target/fse/fsevents.o
>   CXX(target) Release/obj.target/fse/fsevents.o
> In file included from In file included from ../fsevents.cc../fsevents.cc::66:
> :
> ../../nan/nan.h:839:18: ../../nan/nan.h:839warning:: 18: warning: 'MakeCallback''MakeCallback'  isis  deprecated:deprecated:  UseUse  MakeCallback(...,MakeCallback(...,  async_context)async_context)
> 
>             [-Wdeprecated-declarations][-Wdeprecated-declarations]
> 
>     return node::MakeCallback(    return node::MakeCallback(
> 
>                  ^                 ^
> 
> /Users/z002l4q/.node-gyp/10.9.0/include/node/node.h/Users/z002l4q/.node-gyp/10.9.0/include/node/node.h::171171::11::  notenote: : 'MakeCallback''MakeCallback'  hashas  beenbeen explicitly  explicitlymarked  markeddeprecated 
> deprecated      
> here      here
> 
> NODE_DEPRECATED("Use MakeCallback(..., async_context)",NODE_DEPRECATED("Use MakeCallback(..., async_context)",
> 
> ^^
> 
> /Users/z002l4q/.node-gyp/10.9.0/include/node/node.h/Users/z002l4q/.node-gyp/10.9.0/include/node/node.h::8888::2020::  notenote: : expandedexpanded  fromfrom  macromacro  'NODE_DEPRECATED''NODE_DEPRECATED'
> 
>     __attribute__((deprecated(message))) declarator    __attribute__((deprecated(message))) declarator
> 
>                    ^                   ^
> 
> In file included from In file included from ../fsevents.cc../fsevents.cc::66:
> :
> ../../nan/nan.h../../nan/nan.h::854854::1818::  warningwarning: : 'MakeCallback''MakeCallback'  isis  deprecated:deprecated:  UseUse  MakeCallback(...,MakeCallback(...,  async_context)async_context)
> 
>             [-Wdeprecated-declarations][-Wdeprecated-declarations]
> 
>     return node::MakeCallback(    return node::MakeCallback(
> 
>                  ^                 ^
> 
> /Users/z002l4q/.node-gyp/10.9.0/include/node/node.h/Users/z002l4q/.node-gyp/10.9.0/include/node/node.h::164164::11::  notenote: : 'MakeCallback''MakeCallback'  hashas  beenbeen  explicitlyexplicitly  markedmarked  deprecateddeprecated
> 
>             herehere
> 
> NODE_DEPRECATED("Use MakeCallback(..., async_context)",NODE_DEPRECATED("Use MakeCallback(..., async_context)",
> 
> ^^
> 
> /Users/z002l4q/.node-gyp/10.9.0/include/node/node.h/Users/z002l4q/.node-gyp/10.9.0/include/node/node.h::8888::2020::  notenote: : expandedexpanded  from frommacro  macro'NODE_DEPRECATED' 'NODE_DEPRECATED'
> 
>     __attribute__((deprecated(message))) declarator
>     __attribute__((deprecated(message))) declarator
>                    ^
>                    ^
> In file included from ../fsevents.cc:6:
> ../../nan/nan.h:In file included from 869../fsevents.cc::186::
>  ../../nan/nan.h:warning869: :18:'MakeCallback'  is warningdeprecated::  Use 'MakeCallback'MakeCallback(...,  isasync_context) deprecated:
>        Use[-Wdeprecated-declarations] MakeCallback(...,
>  async_context)
>       [-Wdeprecated-declarations]
>     return node::MakeCallback(
>                  ^
>     return node::MakeCallback(
> /Users/z002l4q/.node-gyp/10.9.0/include/node/node.h                 ^:
> 157:1: /Users/z002l4q/.node-gyp/10.9.0/include/node/node.h:157note:: 1:'MakeCallback'  has notebeen:  explicitly'MakeCallback'  markedhas  deprecatedbeen
>        explicitlyhere marked
>  deprecated
>       here
> NODE_DEPRECATED("Use MakeCallback(..., async_context)",
> ^
> NODE_DEPRECATED("Use MakeCallback(..., async_context)",
> /Users/z002l4q/.node-gyp/10.9.0/include/node/node.h^:
> 88:20: /Users/z002l4q/.node-gyp/10.9.0/include/node/node.h:88note:: 20:expanded  from notemacro:  'NODE_DEPRECATED'expanded 
> from macro 'NODE_DEPRECATED'
>     __attribute__((deprecated(message))) declarator
>                    ^
>     __attribute__((deprecated(message))) declarator
>                    ^
> In file included from ../fsevents.cc:6:
> ../../nan/nan.h:1648:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context)
>       [-Wdeprecated-declarations]
> In file included from ../fsevents.cc:6    return scope.Escape(node::MakeCallback(:
> 
> ../../nan/nan.h                              ^:
> 1648:31: /Users/z002l4q/.node-gyp/10.9.0/include/node/node.hwarning:: 171:1:'MakeCallback'  is notedeprecated::  Use'MakeCallback'  MakeCallback(...,has  async_context)been
>        explicitly[-Wdeprecated-declarations] marked
>  deprecated
>       here
>     return scope.Escape(node::MakeCallback(
> NODE_DEPRECATED("Use MakeCallback(..., async_context)",                              ^
> 
> ^
> /Users/z002l4q/.node-gyp/10.9.0/include/node/node.h/Users/z002l4q/.node-gyp/10.9.0/include/node/node.h::17188::120::  notenote: : 'MakeCallback'expanded  hasfrom  beenmacro  explicitly'NODE_DEPRECATED' marked
>  deprecated
>       here
>     __attribute__((deprecated(message))) declarator
>                    ^
> NODE_DEPRECATED("Use MakeCallback(..., async_context)",
> ^
> /Users/z002l4q/.node-gyp/10.9.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
>     __attribute__((deprecated(message))) declarator
>                    ^
> In file included from ../fsevents.cc:85:
> ../src/methods.cc:14:In file included from 12:../fsevents.cc :85:
> warning: ../src/methods.cc:14:'Call'12 :is  deprecated [-Wdeprecated-declarations]warning
> : 'Call' is  handler->Call(3, argv);
>  deprecated           ^
>  [-Wdeprecated-declarations]
> ../../nan/nan.h:1567:3: note: 'Call'  handler->Call(3, argv); 
> has been           ^ 
> explicitly marked deprecated here../../nan/nan.h
> :1567:3: note:   NAN_DEPRECATED inline v8::Local<v8::Value>
> 'Call'  ^
>  has been ../../nan/nan.hexplicitly:98 :marked40 :deprecated  herenote
> : expanded from macro 'NAN_DEPRECATED'
>   NAN_DEPRECATED inline v8::Local<v8::Value># define NAN_DEPRECATED __attribute__((deprecated))
> 
>                                        ^
>   ^
> ../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
> # define NAN_DEPRECATED __attribute__((deprecated))
>                                        ^
> 5 warnings generated.
> 5 warnings generated.
> rm: ./Release/.deps/Release/obj.target/fse/fsevents.o.d.raw: No such file or directory
> make[1]: *** [Release/obj.target/fse/fsevents.o] Error 1
> gyp  SOLINK_MODULE(target) Release/fse.node
>  ERR! build error 
> [...]

`fsevents` doesn't apparently provide pre-build binaries for 1.1.3 using node 10.9.0, and clearly compiling from source fails as well.  However, v1.1.3 is explicitly listed in the `package-lock.json`json file.  If I remove that file, then everything builds and I end up with v1.2.4.  

Would you consider updating the version of `fsevents` this depends on?

**Comment by jburns12** [comment]
Thanks for bringing this up @DavidJBianco . The team will chat about this on Monday to see when we can get this updated. I'll keep you posted!

**Comment by jburns12** [comment]
Hi @vicky-ray - we are hoping to address this as soon as one of our developers is available to do an update/release of the Navigator. For now I'd recommend using David's fix. Sorry about the delay!

**Comment by isaisabel** [comment]
I tried a fresh install of our master branch and encountered the same error. I've updated our package.json with newer versions which seems to have fixed the issue. This fix is currently on the `develop` branch.

Please let us know if you run into any additional errors.

**Comment by isaisabel** [comment]
Note: as part of this fix we updated our Angular version to 7.0.6. This requires a newer nodejs version than our previous Angular requirement, so if you get errors first try updating nodejs to the latest version.

**Comment by vicky-ray** [comment]
thanks @jburns12 and @isaisabel
