### ISSUE TITLE
Initialize multiplyed layers during bootup

### ISSUE THREAD

**Issue by DpoBoceka** [mitre/attack-navigator#67]
Hello. 
I have my Windows-covered layer as a default one and I am able to automatically view it every time I open the web app. But now I'm in need with using another one regarding linux tactics, but I can't have my default layer to serve both platforms because some tactics are in common for each one and covered  diffirently up.
I didn't find any instruction at wiki regarding autoloading layear unless it's default one.

**Comment by isaisabel** [comment]
This feature has been implemented in the [feature/multiple-default-layers](https://github.com/mitre/attack-navigator/tree/feature/multiple-default-layers) branch and merged into develop. The default layer configuration has changed. Here's the new documentation in the readme for quick reference:

>## Loading Default Layers Upon Initialization
>The Navigator can be configured so as to load a set of layers upon initialization. These layers can be from the web and/or from local files. 
>Local files to load should be placed in the `nav-app/src/assets/` directory.
>1. Set the `enabled` property in `default_layers` in `src/assets/config.json` to `true`
>2. Add the paths to your desired default layers to the `urls` array in `default_layers`. For example,
>   ```JSON
>   "default_layers": {
>        "enabled": true,
>         "urls": [
>             "assets/example.json", 
>             "https://raw.githubusercontent.com/mitre/attack-navigator/master/layers/data/samples/Bear_APT.json"
>         ]
>     }
>    ```
>    would load `example.json` from the local assets directory, and `Bear_APT.json` from this repo's sample layer folder on Github.
> 3. Load/reload the Navigator
> 
> A single default layer from the web can also be set using a query string in the Navigator URL. Refer to the in-application help page section "Customizing the Navigator" for more details.
