### ISSUE TITLE
Adding ability to load layers from a URL

### ISSUE THREAD

**Issue by jburns12** [mitre/attack-navigator#7]
This would allow a user to specify a URL to load a layer from in addition to being able to open a local file.

**Comment by thatfiferguy** [comment]
Feature implemented in branch [features/load-layer-from-url](https://github.com/mitre/attack-navigator/tree/features/load-layer-from-url) and merged into develop. Successfully loads a layer from [this raw example layer file](https://raw.githubusercontent.com/mitre/attack-navigator/master/layers/data/samples/Bear_APT.json) hosted on this repository.
