### ISSUE TITLE
Extending technique context menu

### ISSUE THREAD

**Issue by jburns12** [mitre/attack-navigator#9]
As an administrator of Navigator instances, I would like the ability to customize the context menu that is brought up when you right-click on a technique.  Specifically I would like to be able to configure the Navigator to add menu items to the end of the menu and specify a URL to call out when selected. The Navigator would pass info such as the technique ID, tactic, etc. as part of the URL.

**Comment by CollinFingar** [comment]
The addition was pushed to develop with a write-up on how to custom create context menu options.
